export enum ROUTES {
  HOME = '/',
  INTRO_WHY = '/intro/why',
  INTRO_WHAT = '/intro/what',
  DESIGN_LANDING = '/design/landing',
  DESIGN_RULES_ARTICLE_INTRO = '/design/rulesArticleIntro',
  DESIGN_OPTIONAL_FIELD = '/design/OptionalField',
  DESIGN_ONE_COLUMN = '/design/oneColumn',
  DESIGN_ARRANGE_LIST_CHECK_BOXES_VERTICALLY = '/design/arrangeListCheckBoxesVertically',
  DESIGN_DONT_SPLIT_NUMBERS = '/design/dontSplitNumbers',
  DESIGN_PLACEHOLDER = '/design/placeholder',
  DESIGN_WITHOUT_MOUSE = '/design/withoutMouse',
  DESIGN_INLINE_VALIDATION = '/design/inlineValidation',
  DESIGN_SUBMIT_BUTTON = '/design/submitButton',
  DESIGN_BUTTONS_LEFT = '/design/buttonsLeft',
  DESIGN_FINAL_HINTS = '/design/finalHints',
  FORM_STATE_INTRO = '/formState/intro',
  FORM_STATE_NEED_STATE = '/formState/needState',
  FORM_STATE_PURE_HTML = '/formState/pureHTML',
  FORM_STATE_REACT = '/formState/react',
  FORM_STATE_UNCONTROLLED = '/formState/uncontrolled',
  FORM_STATE_UNCONTROLLED_WITH_DEFAULT = '/formState/uncontrolledWithDefault',
  FORM_STATE_CONTROLLED = '/formState/controlled',
  FORM_STATE_WHEN_UNCONTROLLED = '/formState/whenUncontrolled',
  FORM_STATE_WHEN_CONTROLLED = '/formState/whenControlled',
  FORM_STATE_MANAGEMENT_LIBRARIES = '/formState/managementLibraries',
  FORM_STATE_REACT_HOOK_FORM_INTRO = '/formState/reactHookFormIntro',
  FORM_STATE_REACT_HOOK_FORM_FIRST_EXAMPLE = '/formState/reactHookFormFirstExample',
  FORM_STATE_REACT_HOOK_FORM_FIRST_FEATURES = '/formState/reactHookFormFirstFeatures',
  FORM_STATE_REACT_HOOK_FORM_PERFORMANCE = '/formState/reactHookFormFirstPerformance',
  FORM_STATE_REACT_HOOK_FORM_PERFORMANCE_WITH_VALUES = '/formState/reactHookFormFirstPerformanceWithValues',
  FORM_STATE_NEXT_STEP = '/formState/nextStep',
  YUP_LANDING = '/yup/landing',
  YUP_TYPESCRIPT = '/yup/typescript',
  YUP_TYPING_SCHEMAS = '/yup/typing',
}

export const ROUTES_MAP = Object.values(ROUTES);
